# Generated by Django 5.0.3 on 2024-03-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileira', models.PositiveSmallIntegerField()),
                ('numero', models.CharField(max_length=1)),
                ('classe', models.CharField(max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assentos_reservados', models.ManyToManyField(to='reservas.assento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.usuario')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.voo')),
            ],
        ),
        migrations.AddField(
            model_name='assento',
            name='voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.voo'),
        ),
    ]
