# Generated by Django 5.0.3 on 2024-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_assento_voo_reserva_assento_voo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='senha_padrao', max_length=255),
        ),
    ]
