# Generated by Django 5.0.3 on 2024-03-24 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_admin_email_admin_admin_nome_admin_admin_senha_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voo',
            old_name='horario',
            new_name='horario_chegada',
        ),
        migrations.AddField(
            model_name='voo',
            name='estado_origem',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='horario_saida',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
