# Generated by Django 5.0.3 on 2024-03-24 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_rename_horario_voo_horario_chegada_voo_estado_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='estado_destino',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
