# Generated by Django 5.0.3 on 2024-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_usuario_cpf_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voo',
            name='estado_destino',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='estado_origem',
        ),
        migrations.AddField(
            model_name='voo',
            name='assentos',
            field=models.DecimalField(decimal_places=0, default='133', max_digits=10),
        ),
        migrations.AddField(
            model_name='voo',
            name='id_voo',
            field=models.CharField(default=554, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='preco_economica',
            field=models.DecimalField(decimal_places=2, default=556, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voo',
            name='preco_executiva',
            field=models.DecimalField(decimal_places=2, default=5578, max_digits=10),
            preserve_default=False,
        ),
    ]
